import { z } from "zod";

export const courseSchema = z.object({
  id: z.string().uuid(),
  domain: z.enum(["design", "technology", "management"]).default("design"),
  category: z.string(),
  name: z.string(),
  workload_level: z.enum(["light", "balanced", "heavy"]),
  recommended_cpu: z.string().nullable().optional(),
  recommended_gpu: z.string().nullable().optional(),
  recommended_ram: z.string().nullable().optional(),
  recommended_storage: z.string().nullable().optional(),
  recommended_display: z.string().nullable().optional(),
  sort_order: z.number().int().default(0),
  is_active: z.boolean().default(true),
  created_at: z.string(),
  updated_at: z.string().nullable().optional(),
});

export const laptopSchema = z.object({
  id: z.string().uuid(),
  slug: z.string(),
  domain: z.enum(["design", "technology", "management"]).default("design"),
  name: z.string().min(1, "Name is required"),
  brand: z.string().nullable().optional(),
  model: z.string().nullable().optional(),
  price_approx: z.number().int().nullable().optional(),
  price_label: z.string().nullable().optional(),
  amazon_affiliate_url: z.string().url("Must be a valid URL"),
  asin: z.string().nullable().optional(),
  image_url: z.string().url().nullable().optional(),
  cpu: z.string().nullable().optional(),
  gpu: z.string().nullable().optional(),
  gpu_vram_gb: z.number().nullable().optional(),
  ram: z.string().nullable().optional(),
  ram_gb: z.number().int().nullable().optional(),
  storage: z.string().nullable().optional(),
  storage_gb: z.number().int().nullable().optional(),
  display: z.string().nullable().optional(),
  weight: z.string().nullable().optional(),
  os: z.string().nullable().optional(),
  tier: z.enum(["budget", "value", "balanced", "advanced", "premium"]).nullable().optional(),
  workload_tags: z.array(z.string()).default([]),
  recommended_for_courses: z.array(z.string()).default([]),
  not_ideal_for: z.array(z.string()).default([]),
  why_recommended: z.string().nullable().optional(),
  cautions: z.string().nullable().optional(),
  upgrade_notes: z.string().nullable().optional(),
  four_year_suitability: z.enum(["basic", "good", "strong", "excellent"]).nullable().optional(),
  priority_score: z.number().int().default(50),
  is_published: z.boolean().default(false),
  feature_on_home: z.boolean().default(false),
  last_checked: z.string().nullable().optional(),
  raw_input: z.string().nullable().optional(),
  openai_processed_json: z.record(z.string(), z.unknown()).nullable().optional(),
  created_by: z.string().nullable().optional(),
  created_at: z.string(),
  updated_at: z.string(),
});

// Schema for creating/editing a laptop (omits server-managed fields)
export const laptopFormSchema = z.object({
  name: z.string().min(1, "Name is required"),
  domain: z.enum(["design", "technology", "management"]).default("design"),
  brand: z.string().optional(),
  model: z.string().optional(),
  price_approx: z.number().int().min(0).optional().or(z.literal("")),
  price_label: z.string().optional(),
  amazon_affiliate_url: z.string().url("Must be a valid URL"),
  asin: z.string().optional(),
  image_url: z.string().url().optional().or(z.literal("")),
  cpu: z.string().optional(),
  gpu: z.string().optional(),
  gpu_vram_gb: z.union([z.number().min(0), z.string(), z.literal("")]).optional(),
  ram: z.string().optional(),
  ram_gb: z.number().int().min(0).optional().or(z.literal("")),
  storage: z.string().optional(),
  storage_gb: z.number().int().min(0).optional().or(z.literal("")),
  display: z.string().optional(),
  weight: z.string().optional(),
  os: z.string().optional(),
  tier: z.enum(["budget", "value", "balanced", "advanced", "premium"]).optional(),
  workload_tags: z.array(z.string()).default([]),
  recommended_for_courses: z.array(z.string()).default([]),
  not_ideal_for: z.array(z.string()).default([]),
  why_recommended: z.string().optional(),
  cautions: z.string().optional(),
  upgrade_notes: z.string().optional(),
  four_year_suitability: z.enum(["basic", "good", "strong", "excellent"]).optional(),
  priority_score: z.number().int().min(0).max(100).default(50),
  is_published: z.boolean().default(false),
  raw_input: z.string().optional(),
});

export const processedLaptopInputSchema = z.object({
  name: z.string(),
  brand: z.string().optional(),
  model: z.string().optional(),
  price_approx: z.number().int().optional(),
  price_label: z.string().optional(),
  asin: z.string().optional(),
  image_url: z.string().url().optional(),
  amazon_affiliate_url: z.string().url().optional(),
  cpu: z.string().optional(),
  gpu: z.string().optional(),
  gpu_vram_gb: z.number().optional(),
  ram: z.string().optional(),
  ram_gb: z.number().int().optional(),
  storage: z.string().optional(),
  storage_gb: z.number().int().optional(),
  display: z.string().optional(),
  weight: z.string().optional(),
  os: z.string().optional(),
  tier: z.enum(["budget", "value", "balanced", "advanced", "premium"]).optional(),
  workload_tags: z.array(z.string()).optional(),
  recommended_for_courses: z.array(z.string()).optional(),
  not_ideal_for: z.array(z.string()).optional(),
  why_recommended: z.string().optional(),
  cautions: z.string().optional(),
  upgrade_notes: z.string().optional(),
  four_year_suitability: z.enum(["basic", "good", "strong", "excellent"]).optional(),
  priority_score: z.number().int().optional(),
});

export const filterStateSchema = z.object({
  course: z.string().optional(),
  courseCategory: z.string().optional(),
  maxBudget: z.number().int().optional(),
  minRamGb: z.number().int().optional(),
  minVramGb: z.number().optional(),
  tier: z.enum(["budget", "value", "balanced", "advanced", "premium"]).optional(),
  workloadTags: z.array(z.string()).default([]),
  searchQuery: z.string().default(""),
  brand: z.string().optional(),
  processorType: z.string().optional(),
});
